#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f topLayer.vcd

#run Verilator to translate Verilog into C++ testbench
verilator -Wall --cc --trace topLayer.sv --exe topLayer_tb.cpp

#build c++ project via make automatically generated by Verilator 
make -j -C obj_dir/ -f VtopLayer.mk VtopLayer

#run executable simulation file
obj_dir/VtopLayer


